manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
      
      # LS Test to integreate zmk helpers 
    - name: zmk-helpers
      remote: zmkfirmware
      revision: main
      path: modules/zmk-helpers
  self:
    path: config
